name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_config: ^2.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/shared_ui/assets/images/home_icon.png
    - lib/shared_ui/assets/images/favorite_icon.png
    - lib/shared_ui/assets/images/search_icon.png
    - lib/shared_ui/assets/images/profile_icon.png
    - lib/shared_ui/assets/images/app_bar_logo.png
