name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_config: ^2.0.0
  carousel_slider: ^4.2.1
  image: ^3.0.2
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.5
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  image_picker: ^0.8.7+4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/shared_ui/assets/images/home_icon.svg
    - lib/shared_ui/assets/images/home_icon.svg
    - lib/shared_ui/assets/images/favorite_icon.svg
    - lib/shared_ui/assets/images/search_icon.svg
    - lib/shared_ui/assets/images/profile_icon.svg
    - lib/shared_ui/assets/images/primary_long_logo.png
    - lib/shared_ui/assets/images/primary_short_logo.png
    - lib/shared_ui/assets/images/trending_icon.svg
    - lib/shared_ui/assets/images/tv_show_icon.svg
    - lib/shared_ui/assets/images/best_drama_icon.svg
    - lib/shared_ui/assets/images/upcoming_icon.png
    - lib/shared_ui/assets/images/background.png

